import { ArrowUpRight, ShieldCheck } from 'lucide-react';
const cases=[
  {id:'CR-001',area:'WEB—FILESYSTEM',title:'The preview server was also a file server',outcome:'Source map → source code → live database',status:'DUP',href:'/research/preview-server-file-disclosure'},
  {id:'CR-002',area:'WEB—BROWSER',title:'The browser remembered yes. The preview used it.',outcome:'Stored permission → silent audio capture',status:'DUP',href:'/research/microphone-permission-delegation'},
  {id:'CR-003',area:'WEB—AUTH',title:'The interface required SMS. The endpoint did not.',outcome:'Alternate path → missing step-up proof',status:'PAID',href:'/research/sms-step-up-totp-enrollment'},
];
export default function Home(){return <main>
  <header className="site-header shell"><a className="brand" href="/"><span className="brand-mark">V/A</span><span>validbyaccident</span></a><nav><a href="/research">Index</a><a href="/notes">Field notes</a><a href="/about">Identity</a></nav></header>
  <section className="hero shell"><div className="hero-copy"><p className="eyebrow"><span className="live-dot"/> Majd Chorfi · Independent security researcher</p><h1>Research across<br/><i>complex products.</i></h1><p className="lede">I investigate browser, cloud, web, and desktop attack surfaces, with an emphasis on reproducible behavior and clear security impact.</p><div className="hero-actions"><a className="primary-link" href="/research">Enter the index <ArrowUpRight size={16}/></a><a className="text-link" href="/notes">Read the field notes</a></div></div>
    <aside className="lab-note"><div className="panel-label">Research profile / active</div><div className="coordinate">MAJD CHORFI<br/><span>INDEPENDENT / RESEARCH</span></div><dl><div><dt>Surface 01</dt><dd>Browsers & embedded trust</dd></div><div><dt>Surface 02</dt><dd>Cloud authorization</dd></div><div><dt>Surface 03</dt><dd>Desktop attack paths</dd></div></dl><div className="policy"><ShieldCheck size={17}/><span>Public records are sanitized and published through coordinated disclosure.</span></div></aside>
  </section>
  <div className="ticker"><span>PROGRAMS TESTED / GOOGLE / CHROME / VS CODE / ADOBE / FIGMA / HUBSPOT / PINTEREST / PLAID / KUCOIN / 1INCH /</span><span>PROGRAMS TESTED / GOOGLE / CHROME / VS CODE / ADOBE / FIGMA / HUBSPOT / PINTEREST / PLAID / KUCOIN / 1INCH /</span></div>
  <section className="case-section shell"><div className="section-heading"><div><p className="eyebrow">Research index</p><h2>Selected investigations.</h2></div><a className="text-link" href="/research">Full index <ArrowUpRight size={15}/></a></div><div className="case-grid">{cases.map((item,index)=><a className="case-card" href={item.href} key={item.id}><div className="case-meta"><span>{item.id}</span><span>0{index+1} / 03</span></div><div><span className="case-area">{item.area}</span><h3>{item.title}</h3><p>{item.outcome}</p></div><div className="case-footer"><span className="status">{item.status}</span><span>Published research</span></div></a>)}</div></section>
  <section className="human-machine shell"><div className="hm-label"><span>H</span><p>Human</p></div><div className="hm-copy"><p className="eyebrow">A working position for the AI era</p><h2>More paths.<br/><i>Better judgment.</i></h2><p>Artificial intelligence gives me breadth: more comparisons, more variations, and more ways to question the same behavior. The human brain brings context, doubt, ethics, and the instinct to notice when something ordinary is actually strange.</p><p>Used together, one keeps the search moving. The other keeps it honest.</p><a className="primary-link inverse" href="/notes">Read the field notes <ArrowUpRight size={16}/></a></div><div className="hm-label machine"><span>×</span><p>Machine</p></div></section>
  <footer className="site-footer shell"><div><strong>Majd Chorfi</strong><span>validbyaccident · Independent security research</span></div><div className="profile-links" aria-label="Research profiles"><span>HackerOne</span><span>HackenProof</span><span>Google VRP</span><span>X</span><span>LinkedIn</span></div><a href="/about">Contact / disclosure</a></footer>
</main>}
