export type ResearchSection = { heading: string; paragraphs: string[]; code?: string };
export type ResearchRecord = {
  slug: string; id: string; area: string; category: string; status: 'PAID'|'DUP'; published: string; title: string; deck: string; opening: string;
  access: string; result: string; impact: string; note: string; sections: ResearchSection[];
};

export const researchRecords: ResearchRecord[] = [
  {
    slug:'microphone-permission-delegation',id:'CR-002',area:'Browser',category:'WEB—BROWSER',status:'DUP',published:'01 SEP 2026',title:'The browser remembered yes. The preview used it.',
    deck:'An application delegated microphone access to cross-origin code written by its users. One shared project link was enough to turn an old permission grant into live audio capture.',
    opening:'I was checking the permissions attached to a project preview, not trying to attack the microphone. Then I saw allow="microphone" on an iframe whose contents were controlled by whoever created the project.',
    access:'Shared project link',result:'Duplicate / resolved',impact:'Silent audio transcription',note:'The affected AI application builder is unnamed. Project URLs, preview domains, identifiers, and captured test speech are removed.',
    sections:[
      {heading:'A trusted page framing untrusted code',paragraphs:['The main application offered a voice feature, so users had a legitimate reason to grant it microphone access. Project previews ran on another origin and could contain attacker-authored JavaScript. The parent nevertheless delegated microphone permission to every preview iframe.','That combination mattered more than either feature alone. The browser was not bypassed. It followed the permission policy the product had configured. The mistake was treating arbitrary preview code as worthy of a first-party capability.'],code:'<iframe\n  src="https://<project-preview>"\n  allow="fullscreen; camera; microphone; geolocation; ...">'},
      {heading:'The comparison that proved the boundary',paragraphs:['Opening the preview origin directly produced a microphone permission prompt. Opening the same code inside the application did not. The embedded preview inherited the authority already granted to the parent.','My test project started speech recognition, captured a controlled phrase, and sent the transcript to a server I controlled. The request arrived without a new consent prompt. The victim only had to open the shared project while the earlier microphone grant remained valid.']},
      {heading:'Why this was a High-impact finding',paragraphs:['The result was live audio leaving the victim’s browser under the identity and trust of the main application. No exploit warning explained that code inside a shared project—not the voice assistant—had activated the microphone.','A previous grant and a link visit are real prerequisites, but they do not make silent audio capture minor. Active users were exactly the people most likely to have granted the permission already, and shared previews were a normal product workflow.']},
      {heading:'Why the permission prompt did not return',paragraphs:['The earlier permission decision belonged to the top-level application. Permissions Policy then made that capability available to the framed preview. From the browser’s point of view, access had already been granted and delegated, so there was no second decision to ask the user about.','The malicious project did not need to break out of its origin. It called ordinary browser APIs from inside the exact frame to which the parent had granted microphone access. SpeechRecognition produced text, while getUserMedia confirmed the active audio track; the transcript then left through an ordinary outbound request.','The report was a duplicate, explicitly matched to the same microphone-delegation behavior. The fix needed to remove unconditional delegation or place attacker-authored previews behind a permission boundary that could not inherit the parent’s grant.']},
    ]
  },
  {
    slug:'sms-step-up-totp-enrollment',id:'CR-003',area:'Auth',category:'WEB—AUTH',status:'PAID',published:'01 SEP 2026',title:'The interface required SMS. The enrollment endpoint did not.',
    deck:'A crypto account required two verification steps before adding an authenticator. An alternate client path reached the same sensitive action with only the email step.',
    opening:'The settings screen was clear: before a new authenticator could be bound, I had to verify both email and the SMS factor already protecting the account. I wanted to know whether that rule belonged to the server or only to the path the interface normally chose.',
    access:'Session + email code',result:'Paid / resolved',impact:'Unauthorized TOTP binding',note:'The affected exchange is unnamed. Account identifiers, endpoints, verification material, and the bounty amount are omitted.',
    sections:[
      {heading:'Two paths to the same action',paragraphs:['The account-state response told the frontend that SMS-based 2FA was enabled. Changing that client-visible flag did not change the account on the server; it changed which enrollment flow the interface exposed.','The alternate flow asked for an email code and then submitted the TOTP binding request without the SMS proof. The server accepted it. That acceptance—not the local response edit—was the vulnerability.'],code:'Normal state:   "has_2fa": true  → email + SMS → bind TOTP\nModified view: "has_2fa": false → email only  → bind TOTP'},
      {heading:'The missing invariant',paragraphs:['The server knew the account already had SMS protection. It also knew the request was adding a new authentication factor. Those facts should have been enough to enforce SMS step-up regardless of which frontend route produced the request.','Instead, the verification requirement depended on a client-selected workflow. A user interface can guide a security ceremony; it cannot be the authority that decides whether the ceremony happened.']},
      {heading:'What the attacker gained',paragraphs:['With an authenticated session and access to the email code, an attacker could bind an authenticator they controlled without possessing the victim’s SMS factor. That converted compromise of the session and email channel into control of an additional login factor.','The finding did not need a withdrawal demonstration to matter. Adding a durable factor to a financial account is itself a sensitive security change, and the product had explicitly placed SMS in front of it.']},
      {heading:'What the server should have enforced',paragraphs:['The enrollment request should have been evaluated against the account’s actual factor state, not against the frontend route that produced it. If SMS was already bound, the server needed a recent SMS verification artifact tied specifically to adding TOTP.','That check also needed to live on the final binding operation. Validating only an earlier screen or trusting that the client had visited the SMS step would leave the same alternate-path weakness available to direct API requests.','The program paid the report and marked it resolved. The important correction was centralizing the step-up requirement so every enrollment path reached the same server-side decision.']},
    ]
  },
  {
    slug:'ai-widget-origin-trust',id:'CR-004',area:'Browser / AI',category:'WEB—BROWSER/AI',status:'DUP',published:'01 SEP 2026',title:'The first message became the trusted origin.',
    deck:'A frameable AI widget learned its parent origin from the first synchronization message. An external page could claim that trust and fire authenticated CRM actions.',
    opening:'The widget had an origin check. That initially looked reassuring. The problem was where the expected origin came from: the first window that sent the right synchronization message got to define it.',
    access:'Victim logged in',result:'Duplicate / post-fix variant',impact:'Unauthorized AI actions',note:'The CRM vendor, iframe protocol, portal identifiers, component names, and report references are anonymized.',
    sections:[
      {heading:'First message wins',paragraphs:['The cross-window protocol bootstrapped trust during a SYNC exchange. If no parent origin had been recorded yet, a structurally valid message caused the widget to store event.origin as its parent. There was no comparison with a fixed list of legitimate application origins.','Because the widget also lacked an effective framing restriction, an external page could embed it, send SYNC first, and become the trusted host for that instance. Later checks succeeded because the attacker had supplied the value being checked.'],code:'if (!parent.origin && isSync(message)) {\n  parent.origin = event.origin;\n}'},
      {heading:'From frame trust to an AI action',paragraphs:['The iframe URL accepted an action object describing a CRM record to summarize. Loading the widget inside the attacker page, completing the fraudulent handshake, and opening the component caused the authenticated AI pipeline to run in the victim’s portal.','The action created a persistent thread entry and caused the assistant to process the selected CRM object without the victim asking it to. An attacker-controlled name field also entered the prompt, providing a route for persistent misleading AI content.']},
      {heading:'The duplicate that survived the fix',paragraphs:['The report was initially matched to an earlier assistant component that used the same messaging architecture. That was a logical duplicate decision: a complete architectural patch should have fixed both.','After the earlier report was marked resolved, I retested. The separate widget still accepted the attack. The remediation had fixed one deployment of the pattern, not the other. That turned the retest into evidence of an incomplete fix across components sharing the same trust protocol.']},
      {heading:'Why both controls mattered',paragraphs:['A framing restriction would have prevented an arbitrary website from placing the widget in the attacker-controlled parent relationship used by the proof. A fixed origin allowlist in the message handler would have protected the protocol even if the widget was framed somewhere unexpected.','The synchronization protocol also needed to bind the sender window together with an approved origin. Checking only the stored origin after allowing the first sender to populate it turned every later comparison into circular validation.','AI made the consequence unusual, but the failure was classical browser security: an authenticated model pipeline inherited authority from a widget whose parent identity was established by whoever spoke first.']},
    ]
  },
  {
    slug:'client-flags-admin-impersonation',id:'CR-005',area:'Authorization',category:'WEB—AUTHZ',status:'DUP',published:'01 SEP 2026',title:'Changing the role flag opened the door. The API forgot to close it.',
    deck:'Response manipulation exposed an administrative workflow, but the real finding came one request later: a normal user could send staff-branded messages to other users.',
    opening:'Changing isAdmin from false to true made an admin console appear. On its own, that meant almost nothing. Frontends can display whatever a user makes them display. The next request decided whether this was a visual trick or a security boundary.',
    access:'Normal account',result:'Duplicate / resolved',impact:'Staff impersonation',note:'The affected Web3 platform, procedures, wallet addresses, user records, and interface branding are removed.',
    sections:[
      {heading:'Walking through the client gates',paragraphs:['The frontend checked an administrative flag, then an OTP state, then an OTP verification result. Each value arrived in a response the browser trusted to decide what screen came next.','I altered the role and OTP-related responses until the console loaded. That was useful for mapping the hidden workflow, but it was not yet privilege escalation.'],code:'"isAdmin": false   → true\n"otpEnabled": false → true\n{"success": false}  → {"success": true}'},
      {heading:'The request that made it real',paragraphs:['From the exposed console, I started a conversation with a second controlled user. The backend accepted the privileged action using my ordinary session. On the recipient side, the conversation appeared as an official staff interaction.','That proved the server had repeated the frontend’s mistake. It authorized an admin-only function without independently verifying the user’s role and completed step-up state.']},
      {heading:'More than an exposed dashboard',paragraphs:['Staff identity carries trust. A normal user who can contact arbitrary users through an official channel can run targeted phishing and social-engineering campaigns from inside the product. The victim does not see an imitation domain or an external account; the platform itself presents the attacker as staff.','I describe the proven impact as administrative impersonation rather than unlimited platform takeover. That is not a weaker story. It is the precise privileged operation that succeeded end to end.']},
      {heading:'Why the backend accepted it',paragraphs:['The administrative interface supplied the shape of the privileged messaging request: procedure name, target user identifier, message body, and the response the frontend expected. Once the console was visible, those details could be replayed independently of the visual state.','The decisive defect was that the messaging operation trusted the route’s presence in the admin console instead of verifying the caller’s role at the API boundary. The low-privilege session remained unchanged from login through delivery to the second account.','The report was a duplicate. That outcome confirmed the chain was already known, while the two-account proof established that it ended in a real staff-branded action rather than a locally altered dashboard.']},
    ]
  },
  {
    slug:'delegated-request-cross-portal',id:'CR-006',area:'Browser',category:'WEB—BROWSER',status:'PAID',published:'01 SEP 2026',title:'One delegated path crossed into another portal.',
    deck:'Attacker-controlled preview content could choose an internal API path used by an authenticated parent application, turning a message bridge into unauthorized CRM object creation.',
    opening:'The JavaScript ran on a preview domain, which normally limits the impact of an XSS report. The interesting part was not where the script ran. It was what the authenticated parent application agreed to do when that preview sent it a message.',
    access:'Low-privilege author + viewer',result:'Paid / Medium',impact:'Cross-portal CRM writes',note:'The CRM platform, domains, portal IDs, internal message names, report number, and customer data are anonymized.',
    sections:[
      {heading:'A preview talking to the main application',paragraphs:['A low-privilege user could place script-capable content in an email preview. When a more privileged user viewed it, the preview ran inside a frame connected to the main CRM application through postMessage.','The message handler intentionally accepted delegated requests from the preview. The dangerous input was a path field that selected which internal API route the parent would call with the viewer’s authenticated session.']},
      {heading:'Turning a bridge into an API selector',paragraphs:['By changing the delegated path to a CRM object endpoint, the preview caused the parent to submit an authenticated object-creation request. Same-origin and CSRF protections did not stop it because the trusted parent—not the preview—performed the request.'],code:'preview → postMessage({ delegatedPath: "/crm/objects/<type>" })\nparent  → authenticated request using viewer session'},
      {heading:'The cross-portal proof',paragraphs:['The strongest test used two portals. I had only limited content permissions in Portal A and no membership in Portal B. The victim account belonged to both. When that user opened the content from Portal A, the delegated request created CRM data in Portal B with the victim’s authority.','That was a genuine cross-organizational integrity violation. The attack required a dual-member victim and a view of attacker-created content, but the resulting write occurred in an organization the attacker could not access directly.']},
      {heading:'The confirmed root cause',paragraphs:['The program’s engineers identified the arbitrary delegated path as the part that required a fix. The cross-domain message channel itself was intentional; the unsafe behavior was allowing content on the sending side to select a privileged internal route.','Restricting that field to a fixed set of actions changes the bridge from a generic authenticated request proxy into a capability interface. The parent can then validate the exact command, required portal context, permitted HTTP method, and caller authority instead of inheriting them from a string.','The report was paid. Its strongest demonstrated consequence remained the cross-portal write: attacker-authored content in one organization caused an authenticated user’s authority to modify CRM data in another.']},
    ]
  },
  {
    slug:'graphql-wallet-data-idor',id:'CR-007',area:'API',category:'WEB—API',status:'DUP',published:'01 SEP 2026',title:'A wallet address was treated as authorization.',
    deck:'Two GraphQL queries accepted any Ethereum address and returned another account’s rewards and profile records. A second controlled account proved the boundary.',
    opening:'Wallet addresses are public, which makes authorization testing around them easy to get wrong. Seeing an address parameter in a GraphQL query is not automatically an IDOR. I needed to know whether changing it exposed application data that belonged to another account.',
    access:'Authenticated account',result:'Duplicate / resolved',impact:'Cross-account data access',note:'The platform, API hostname, operation names, wallet addresses, and response values are anonymized.',
    sections:[
      {heading:'Two accounts, one substituted variable',paragraphs:['I created a second controlled account and recorded the rewards and profile data visible to it. From the first account, I replayed two GraphQL queries and replaced only the wallet-address variable with the second account’s address.','Both queries returned the second account’s records. One exposed rewards-related information such as points, referral data, TVL, and invite counts. The other returned profile metadata.']},
      {heading:'Why the second account mattered',paragraphs:['My abbreviated proof also used a placeholder-style address, but that alone was not enough. A response for an arbitrary address could have been public blockchain enrichment or empty default data.','The controlled-account comparison established the object boundary: Account A’s authenticated session could request Account B’s application records by naming B’s public address. The server treated knowledge of the identifier as permission.']},
      {heading:'Public identity, private application state',paragraphs:['The key distinction was not whether the wallet address itself was public. It was whether the associated rewards and account fields were intended to be exposed to other signed-in users. Public identifiers still need authorization when they index private off-chain state.','The report was marked as a duplicate of a known issue. I keep that outcome in the article because it confirms independent discovery without pretending I was first.']},
      {heading:'The authorization check that was missing',paragraphs:['Authentication established which wallet controlled the current session. The resolver still accepted a different wallet address as the subject of an account-specific query without checking whether the caller was allowed to read it.','A correct design could either return only intentionally public fields for arbitrary addresses or require the requested address to match the authenticated wallet before returning private rewards and account state. Mixing both data classes in the same unrestricted resolver made the boundary unclear and easy to cross.','The duplicate result showed the behavior was already recognized. The two-account proof supplied the important evidence: the response was not generic chain data, but the other controlled account’s application record.']},
    ]
  },
  {
    slug:'mfa-proof-reuse',id:'CR-008',area:'Auth',category:'WEB—AUTH',status:'PAID',published:'01 SEP 2026',title:'The MFA proof outlived the action it was meant to protect.',
    deck:'A login-time MFA token could authorize enrollment of another authenticator without a fresh challenge, turning temporary authenticated access into a more durable foothold.',
    opening:'At first I thought I had removed MFA by changing an account response. I had not. The server still knew the original factor existed, and the enrollment request still carried proof from the earlier login. The real issue was more subtle: that old proof was accepted for adding a new factor.',
    access:'Strongly authenticated session',result:'Paid / Low',impact:'Additional TOTP binding',note:'The identity platform, token contents, account identifiers, QR codes, report references, and reward are removed.',
    sections:[
      {heading:'The first theory was wrong',paragraphs:['Changing the visible mfa_methods array made the interface show an enrollment flow, but it did not delete anything server-side. The program was right to challenge that interpretation.','Looking at the successful binding request changed the case. It carried the cached MFA proof issued during login, and the server treated that as sufficient authorization to enroll another authenticator.']},
      {heading:'Authentication is not freshness',paragraphs:['A session can prove that MFA happened at some earlier point. A sensitive factor-management action needs a stronger question: did the user prove possession again for this action, recently and intentionally?','The server did not ask that second question. An attacker holding the already authenticated state could bind a TOTP seed they controlled without entering a new code from the victim’s existing authenticator.']},
      {heading:'A persistence bug, not magic account takeover',paragraphs:['The new factor created durable security value for the attacker, but future login still depended on the platform’s email-code flow. The clean impact was unauthorized enrollment of an additional factor and persistence after temporary session access.','The program eventually agreed that enrollment should require MFA again, created an engineering change, paid the highest bounty in its category, and resolved the report at Low severity.']},
      {heading:'What changed in the final report',paragraphs:['The first version focused too much on changing mfa_methods in the response. That modification only unlocked the hidden enrollment screen. The successful server request, and the proof it carried, were the real evidence.','Once the report was framed around proof reuse, the program agreed to change the flow so adding another factor would require MFA again. The finding was paid and resolved as a fresh-verification weakness.','The distinction is important: a token can be authentic, unexpired, and issued after real MFA while still being inappropriate for factor enrollment. Sensitive-action authorization needs purpose and freshness, not only validity.']},
    ]
  },
  {
    slug:'oauth-session-swapping',id:'CR-009',area:'OAuth',category:'WEB—OAUTH',status:'PAID',published:'01 SEP 2026',title:'The callback belonged to the attacker. The browser belonged to the victim.',
    deck:'A missing OAuth request binding let an attacker move their own login callback into another browser, forcing the victim into the attacker’s account context.',
    opening:'I started a normal Google login for my own account and stopped at the application callback. Then I asked a simple OAuth question: what tied this callback to the browser that started it? The answer was nothing I could find.',
    access:'Victim opens crafted callback',result:'Paid / resolved',impact:'Forced login / session swap',note:'The Web3 service, callback domain, account details, exact dates, report references, and proof video are anonymized.',
    sections:[
      {heading:'Moving one login between two browsers',paragraphs:['The attacker began OAuth authentication for an account they controlled, captured the callback containing the authorization code, and prevented their own browser from completing it.','That callback was delivered to a victim. Because the application did not bind the response to the initiating browser with state or an equivalent transaction value, the victim’s browser accepted it and became logged into the attacker’s account.']},
      {heading:'Why forced login matters',paragraphs:['The attacker does not steal the victim’s existing session. Instead, the victim performs later actions inside an account the attacker controls. That session confusion is valuable wherever users submit secrets, connect resources, enter payment information, or complete identity verification after login.','In this product, the post-login flow required identity verification. A victim who did not notice the account context could place sensitive verification material into the attacker-controlled account. The missing binding created that path; the downstream workflow supplied the consequence.']},
      {heading:'The part that deserves careful proof',paragraphs:['The forced-login behavior was demonstrated and the program paid the report. The strongest document-theft outcome additionally depends on what the account owner can retrieve after verification and how clearly the interface identifies the current account.','That does not reduce the core finding. OAuth session swapping is a real cross-browser authentication failure. It simply separates the proven primitive from the most severe application-specific follow-on.']},
      {heading:'What state should have done',paragraphs:['A server-generated state value should have been stored with the browser that initiated login and returned unchanged through the provider. The callback could then be rejected when it arrived without the matching browser-side transaction.','That binding prevents a valid authorization code from becoming portable between users. The code may genuinely represent the attacker’s Google account, but it should complete only the login transaction that requested it.','The report was paid for the forced-login primitive. The surrounding identity-verification flow made the session swap especially dangerous because it encouraged the victim to submit high-value information immediately after authentication.']},
    ]
  },
  {
    slug:'user-record-bola',id:'CR-010',area:'API',category:'WEB—API',status:'PAID',published:'01 SEP 2026',title:'Changing one object ID returned another person’s record.',
    deck:'An authenticated profile lookup returned another user’s personal and KYC-related fields when supplied with that user’s identifier.',
    opening:'The endpoint name was direct: find a user by ID. Direct endpoints are useful during development and dangerous when the object identifier becomes the only authorization check.',
    access:'Any authenticated user',result:'Paid / resolved',impact:'Cross-user PII disclosure',note:'The financial platform, endpoint, identifiers, response bodies, personal data, dates, and reward are anonymized.',
    sections:[
      {heading:'A two-account authorization test',paragraphs:['From one authenticated account, I replaced the ID in the profile request with an identifier belonging to another controlled user. The server returned the other user’s record instead of rejecting the request.','The response included personal and account-related fields such as email, network information, wallet details, and KYC state. The authorization decision was effectively possession of the object ID.']},
      {heading:'The identifier question',paragraphs:['The backend used ObjectId-shaped values, so simple numeric incrementing was not the right scalability argument. The important question was where foreign identifiers appeared elsewhere in the application and whether they could be collected.','The direct cross-account read was proven. Scale depended on ID discovery, and the sensitivity depended on the exact response schema. Those are separate parts of the same risk, not reasons to ignore the BOLA.']},
      {heading:'CORS was not the escalation',paragraphs:['The API returned a wildcard origin together with a credentials flag. Browsers reject credentialed wildcard CORS, so that header pair did not create the malicious-site harvesting path I first described.','The vulnerability did not need CORS. Any authenticated user could call the endpoint directly and retrieve a record they were not authorized to see. The clean report was the server-side object authorization failure.']},
      {heading:'What the authorization check needed',paragraphs:['The endpoint had enough context to identify both the caller and the requested user. Before serializing the profile, it needed to decide whether those identities matched or whether a specific administrative relationship allowed the read.','Field-level response shaping was also relevant. Even where a public profile lookup was intended, internal network values, email, wallet/KYC state, and identity-related fields did not need to travel in the same object.','The program paid the finding and marked it resolved. The controlled-account swap proved the cross-user disclosure directly; identifier discovery determined scale, not whether the authorization failure existed.']},
    ]
  },
  {
    slug:'javascript-logout-redirect',id:'CR-011',area:'XSS',category:'WEB—XSS',status:'PAID',published:'01 SEP 2026',title:'A logout redirect accepted JavaScript as a destination.',
    deck:'A crafted logout URL executed JavaScript on an authentication domain. The initial self-XSS ruling changed once the callback was delivered as a link.',
    opening:'The first reproduction was badly explained. I intercepted my own logout request, changed the redirect, and made the payload execute. Read literally, that looked like self-XSS. The missing step was that the modified request was already a URL an attacker could send to someone else.',
    access:'Victim opens crafted link',result:'Paid / Low',impact:'Script execution on auth origin',note:'The authentication provider, hostname, tenant configuration, user identifiers, report references, and reward are anonymized.',
    sections:[
      {heading:'From self-XSS to a deliverable URL',paragraphs:['The logout endpoint accepted a javascript: value as its post-logout redirect. When a victim visited the crafted URL, the browser completed the logout flow and executed attacker-supplied script in the authentication origin.','No victim had to intercept a request or edit a parameter. Once I provided the direct link, triage reopened the report and validated it as reflected XSS.'],code:'GET /oauth/logout?post_logout_redirect_uri=javascript:<payload>'},
      {heading:'What the script could reach',paragraphs:['The proof read a controlled localStorage value and sent it to a test server. It also had DOM control over a domain users associated with authentication, which made same-origin phishing content possible.','HttpOnly cookies prevented the easiest session-token theft, and logout reduced the value of some authentication state. Those facts shaped the Low rating, but they did not make the JavaScript execution imaginary.']},
      {heading:'Configuration was part of the story',paragraphs:['The program initially described the behavior as customer configuration. I clarified that the affected flow was the provider’s own dashboard logout, not merely an application callback I had configured.','The final resolution added a warning around the risky option, awarded a Low bounty, and changed the report from Informative to Resolved.']},
      {heading:'Why delivery changed the classification',paragraphs:['Intercepting and modifying my own logout request was only the discovery method. The resulting request was a self-contained URL, so the attacker could prepare it in advance and deliver it through an ordinary link. The victim did not edit or knowingly inject anything.','Once that distinction was clear, triage reopened the report and validated reflected XSS. The execution still occurred during logout, which limited some session impact, but the script ran on the trusted authentication origin and could control its DOM and origin-accessible storage.','The report was ultimately paid and resolved at Low. The technical correction came from showing the victim’s shortest path, not from adding a more dramatic payload.']},
    ]
  },
  {
    slug:'race-condition-attempt-counter',id:'CR-012',area:'Concurrency',category:'WEB—RACE',status:'PAID',published:'01 SEP 2026',title:'Ten attempts became as many as I could send at once.',
    deck:'A non-atomic counter charged a parallel batch as a single attempt, letting vendor-association requests exceed the intended limit.',
    opening:'The endpoint gave me ten tries to associate a vendor identifier. I sent several requests together and expected the counter to fall once for each request. It moved by one.',
    access:'Association workflow',result:'Paid / Low',impact:'Attempt-limit bypass',note:'The commerce platform, endpoint, identifiers, report references, dates, and reward are anonymized.',
    sections:[
      {heading:'The counter lost the race',paragraphs:['Parallel requests reached the verification logic before the shared attempt state had been updated consistently. Each request observed essentially the same counter value, and the completed batch consumed fewer attempts than the number processed.','Larger parallel groups reproduced the behavior. The ten-attempt control was not atomic around the check and decrement.'],code:'request A ─┐\nrequest B ─┼─ read attempts = 10 → process → write 9\nrequest C ─┘'},
      {heading:'What was proven',paragraphs:['The proof showed that concurrent requests could exceed the intended attempt allowance. The program classified it as a race condition, paid a bounty, and rated it Low.','I did not have a valid vendor identifier, so I could not demonstrate the successful end of the brute-force path or measure the identifier space. The accepted issue was the broken control itself.']},
      {heading:'A fix that needed another look',paragraphs:['The program later said a fix had reached production. I retested and saw the same counter behavior, then supplied another recording. A later closure again described the issue as fixed, while my last test still reproduced it.','That history is why retesting deserves the same discipline as the original report: a status change is not evidence, and a changed response is not necessarily an atomic fix.']},
      {heading:'What atomic enforcement would change',paragraphs:['The check and decrement needed to happen as one atomic operation or inside a transaction that rejected conflicting updates. Another option was to reserve an attempt before processing the candidate, ensuring every accepted request consumed capacity even when many arrived together.','The control also needed to be keyed to the correct security subject—account, association flow, or vendor challenge—so opening parallel connections or sessions could not create independent counters.','The report was paid as a Low-severity race condition. Retests mattered because a cosmetic response change or delayed counter refresh could leave the underlying concurrent state transition unchanged.']},
    ]
  },
];

export function getResearchRecord(slug: string) { return researchRecords.find(record => record.slug === slug); }
